config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  resources :teams
  get 'pages/info'
  resources :players
  root 'pages#info'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord
	has_many :teams, dependent: :delete_all
	validates :name, :country, presence: true
	validates :website, :format => URI::regexp(%w(http https))

	has_attached_file :logo, styles: { large: "600x600#", medium: "300x300#", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
	validates_attachment_file_name :logo, matches: [/png\z/, /jpe?g\z/]
	validates_with AttachmentSizeValidator, attributes: :logo, less_than: 1.megabytes

	def team_count
		Team.where(league: self).count
	end

	def self.search(term)
  		if term
    		where('name LIKE ?', "%#{term}%")
  		else
    		all
  		end
	end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.search(params[:q])
      .order(sort_column + " " + sort_direction)
      .page(params[:page]).per(6)
    @search = params[:q]
    @display = params[:d]
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :country, :website, :logo, :q, :d)
    end

    def sort_column
      League.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league, local: true) do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.country_select :country, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :website %>
    <%= form.text_field :website, class: "form-control" %>
  </div>

     <% if @league.logo.exists? %>
    <hr class="mb-4">

    <div class="row">
      <div class="form-group col-md-6">
        <%= form.label :logo, "New logo" %>
        <%= form.file_field :logo, class: "form-control-file" %>
        <small class="form-text text-muted">File not bigger than 1MB.</small>
      </div>

      <div class="form-group col-md-6">
        <p>Current logo</p>
        <%= image_tag(league.logo.url(:thumb), class: "img-fluid border rounded") %>
      </div>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :logo %>
      <span class="text-muted">(Optional)</span>
      <%= form.file_field :logo, class: "form-control-file" %>
      <small class="form-text text-muted">File not bigger than 1MB.</small>
    </div>
  <% end %>

  <hr class="mb-4">

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/leagues/_grid.html.erb
<div class="row">
<% @leagues.each do |league| %>
  <div class="col-md-4 d-flex align-items-stretch">
    <div class="card mb-4 box-shadow">
      <% if league.logo.exists? %>
        <%= image_tag(league.logo.url(:large), class: "card-img-top") %>
      <% else %>
        <%= holder_tag '600x600', league.name, 'sky', { class: 'card-img-top' }, { auto: 'yes' } %>
      <% end %>

      <div class="card-body">
        <h4><%= link_to league.name, league, class: "text-dark" %></h4>
        <p class="card-text text-muted"><%= league.country %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <%= link_to 'Edit', edit_league_path(league), class: "btn btn-sm btn-outline-primary" %>
            <%= link_to 'Delete', league, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/leagues/_table.html.erb
<table class="table bg-white">
  <thead class="thead-light">
    <tr>
      <th scope="col"><%= sortable "name" %></th>
      <th scope="col"><%= sortable "country" %></th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @leagues.each do |league| %>
    <tr>
      <td><%= league.name %></td>
      <td><%= league.country %></td>
      <td>
        <%= link_to 'Show', league, class: "btn btn-sm btn-outline-info" %>
        <%= link_to 'Edit', edit_league_path(league), class: "btn btn-sm btn-outline-primary" %>
        <%= link_to 'Delete', league, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/leagues/edit.html.erb
<div class="row">
  <div class="col-md-6 py-5 mx-auto">
    <%= link_to "Show", @league, class: "btn btn-outline-info float-right" %>
    <h4 class="mb-3">Edit league</h4>

    <%= render 'form', league: @league %>
  </div>
</div>

app/views/leagues/index.html.erb
<div class="album py-5">
  <div class="container">

    <% if notice %>
      <p id="notice" class="alert alert-success"><%= notice %></p>
    <% end %>

    <div class="d-flex flex-wrap flex-column flex-sm-row justify-content-between mb-4">
      <%= link_to 'Add league', new_league_path, { :class=>"btn btn-primary mb-2 mb-sm-0" } %>

      <div class="text-nowrap view-opt d-flex justify-content-between">
        <div class="view-group">
          <% if @display == 'grid' %>
            <%= material_icon.view_module.md_24.css_class('btn btn-sm btn-light mr-2 rounded active text-muted') %>
            <%= link_to material_icon.view_list.md_24, leagues_path(:q => @search, :d => "table"), class: "btn btn-sm btn-light mr-2 rounded text-muted" %>
          <% else %>
            <%= link_to material_icon.view_module.md_24, leagues_path(:q => @search, :d => "grid"), class: "btn btn-sm btn-light mr-2 rounded text-muted" %>
            <%= material_icon.view_list.md_24.css_class('btn btn-sm btn-light mr-2 rounded active text-muted') %>
          <% end %>
        </div>
        <%= form_tag(leagues_path, method: :get) do %>
          <div class="input-group d-flex">
            <% if params[:d] %>
              <%= hidden_field_tag :d, params[:d] %>
            <% end %>
            <%= text_field_tag :q, params[:q], class: "form-control" %>
            <div class="input-group-append search-opt">
              <%= button_tag(type: 'submit', name: nil, class: "btn btn-primary") do %>
                <%= material_icon.search %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if @display == 'grid' %>
      <%= render 'grid', team: @team %>
    <% else %>
      <%= render 'table', team: @team %>
    <% end %>

    <% if @leagues.first.nil? %>
      <div class="alert alert-secondary" role="alert">
      No results...
      </div>
    <% end %>

    <%= paginate @leagues %>

  </div>
</div>

app/views/leagues/new.html.erb
<div class="row">
  <div class="col-md-6 py-5 mx-auto">
    <h4 class="mb-3">Add new league</h4>

    <%= render 'form', league: @league %>
  </div>
</div>

app/views/leagues/show.html.erb
<div class="py-5">

  <% if notice %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>

  <div class="row">

    <div class="col-md-6 mb-5">
      <% if @league.logo.exists? %>
        <%= image_tag @league.logo.url(:large), class: "img-fluid border rounded" %>
      <% else %>
        <%= holder_tag '600x600', @league.name, 'sky', { class: 'img-fluid border rounded' }, { auto: 'yes' } %>
      <% end %>
    </div>
   <div class="col-md-6">
     <h2><%= @league.name %></h2>
     <table class="table table-hover">
       <tbody>
         <tr>
           <th scope="row">Country</th>
           <td class="text-right"><%= @league.country %></td>
         </tr>
         <tr>
           <th scope="row">Website</th>
           <td class="text-right"><a href="<%= @league.website %>"><%= @league.website %></a></td>
         </tr>
         <tr>
           <th scope="row">Teams count</th>
           <td class="text-right"><%= @league.team_count %></td>
         </tr>
       </tbody>
     </table>
     <%= link_to "Edit", edit_league_path(@league), class: "btn btn-outline-primary" %>
     <%= link_to 'Delete', @league, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
   </div>
  </div>
</div>