config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  resources :teams
  get 'pages/info'
  resources :players
  root 'pages#info'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="my-md-5 text-center text-muted">
  <div class="container pt-5 border-top">
    <p>© 2018 RailsTeamsApp by OkeyDockey Team</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to "RailsTeamsApp", root_path, { :class=>"navbar-brand" } %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item <%= 'active' if params[:controller] == 'players' %>">
          <%= link_to 'Players', players_path, { :class=>"nav-link" } %>
        </li>
        <li class="nav-item <%= 'active' if params[:controller] == 'teams' %>">
          <%= link_to 'Teams', teams_path, { :class=>"nav-link" } %>
        </li>
        <li class="nav-item <%= 'active' if params[:controller] == 'leagues' %>">
          <%= link_to 'Leagues', leagues_path, { :class=>"nav-link" } %>
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTeamsApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oswald" />
  </head>

  <body>
    <div class="head"></div>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>